мелкая сетка на флексах
htmlacademy-htmlcss/2509131-sedona-1 pull request #6
Opened 2024-04-28 11:51 UTC by Katerina2391

2024-04-29 07:02 UTC, VAnastasia requested changes

2024-04-29 07:02 UTC, VAnastasia commented on styles/styles.css
> +  padding: 0;
2 раза padding задан, padding: 0; отменит padding: 8px 50px;

2024-04-29 07:02 UTC, VAnastasia commented on styles/styles.css
> +}
точка в селекторе по классу потерялась - .hotels-filter-group-living и .hotels-filter-group-price

2024-04-29 07:02 UTC, VAnastasia commented on styles/styles.css
> +  margin-bottom: 46.5px;
margin-bottom 2 раза

2024-04-29 07:02 UTC, VAnastasia commented on styles/styles.css
>    }
цвет надо маленькими буквами по кодгайду #f2f2f2, и закрывающая фигурная скобка местами съезжает

2024-05-01 12:08 UTC, Katerina2391 commented
исправила

2024-05-01 12:14 UTC, merged